workflows:
  android-workflow:
    name: WillFiles Android Build

    environment:
      flutter: stable

    scripts:
      - flutter pub get
      - flutter build apk --release

      - build/app/outputs/flutter-apk/app-release.a
